### ISSUE TITLE
OSError: [WinError 126] 找不到指定的模块。

### ISSUE THREAD

**Issue by uncle2** [chineseocr/table-ocr#10]
求大神指导，这个报错是怎么回事
Traceback (most recent call last):
  File "table.py", line 22, in <module>
    from darknet import  load_net,predict_image,array_to_image
  File "D:\table-ocr-master\table-ocr-master\darknet.py", line 52, in <module>
    lib = CDLL(darkRoot, RTLD_GLOBAL)
  File "D:\python3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by Sukeysun** [comment]
请问这个问题解决了吗 我也遇到了

**Comment by huabao97** [comment]
我也是
