### ISSUE TITLE
运行出错，求救！

### ISSUE THREAD

**Issue by eratio** [chineseocr/table-ocr#2]
Traceback (most recent call last):
  File "table.py", line 209, in <module>
    rboxes,ColsLines,RowsLines = get_table_ceilboxes(img,prob=0.5,row=10,col=10,alph=10)
  File "table.py", line 173, in get_table_ceilboxes
    RowsLines,ColsLines=get_table_rowcols(img,prob,row,col)
  File "table.py", line 94, in get_table_rowcols
    xmin,xmax = indX.min(),indX.max()
  File "/home/ubuntu/anaconda3/envs/ai/lib/python3.6/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by eratio** [comment]
好像关闭GPU选项，就正常了。求教作者大神是什么原因？

**Comment by tangent2018** [comment]
看报错内容，模型识别出来的结果是空的所以xmin,xmax = indX.min(),indX.max()这里没法计算。要多做个对空的结果的判断，应该与CPUGPU没关系
